DROP DATABASE IF EXISTS usflights;
CREATE DATABASE usflights;
\c usflights

DROP TABLE IF EXISTS Flights;
DROP TABLE IF EXISTS Carriers;
DROP TABLE IF EXISTS USAirports;

CREATE TABLE USAirports (
    IATA      varchar(32) PRIMARY KEY,
    Airport   varchar(80),
    City      varchar(32),
    State     varchar(32),
    Country   varchar(32),
    Latitude  double precision,
    Longitude double precision
);

CREATE TABLE Carriers (
    CarrierCode varchar(32) PRIMARY KEY,
    Description varchar(120)
);

CREATE TABLE Flights (
    flightID          int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    colYear           smallint,
    colMonth          smallint,
    DayOfMonth        smallint,
    DayOfWeek         smallint,
    DepTime           smallint,
    CRSDepTime        smallint,
    ArrTime           smallint,
    CRSArrTime        smallint,
    UniqueCarrier     varchar(32),
    FlightNum         varchar(32),
    TailNum           varchar(32),
    ActualElapsedTime smallint,
    CRSElapsedTime    smallint,
    AirTime           smallint,
    ArrDelay          smallint,
    DepDelay          smallint,
    Origin            varchar(32),
    Dest              varchar(32),
    Distance          smallint,
    TaxiIn            smallint,
    TaxiOut           smallint,
    Cancelled         boolean,
    CancellationCode  varchar(32),
    Diverted          boolean,
    CarrierDelay      smallint,
    WeatherDelay      smallint,
    NASDelay          smallint,
    SecurityDelay     smallint,
    LateAircraftDelay smallint,
    CONSTRAINT flights_dest_fk    FOREIGN KEY (Dest)          REFERENCES USAirports (IATA),
    CONSTRAINT flights_origin_fk  FOREIGN KEY (Origin)        REFERENCES USAirports (IATA),
    CONSTRAINT flights_carrier_fk FOREIGN KEY (UniqueCarrier) REFERENCES Carriers (CarrierCode)
);

CREATE INDEX idx_flights_dest    ON Flights (Dest);
CREATE INDEX idx_flights_origin  ON Flights (Origin);
CREATE INDEX idx_flights_carrier ON Flights (UniqueCarrier);

